//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ActivityMDModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ActivityMDEntities2 : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ActivityMDEntities2”部分中的连接字符串初始化新 ActivityMDEntities2 对象。
        /// </summary>
        public ActivityMDEntities2() : base("name=ActivityMDEntities2", "ActivityMDEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ActivityMDEntities2 对象。
        /// </summary>
        public ActivityMDEntities2(string connectionString) : base(connectionString, "ActivityMDEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ActivityMDEntities2 对象。
        /// </summary>
        public ActivityMDEntities2(EntityConnection connection) : base(connection, "ActivityMDEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbComment> tbComment
        {
            get
            {
                if ((_tbComment == null))
                {
                    _tbComment = base.CreateObjectSet<tbComment>("tbComment");
                }
                return _tbComment;
            }
        }
        private ObjectSet<tbComment> _tbComment;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbStatistics> tbStatistics
        {
            get
            {
                if ((_tbStatistics == null))
                {
                    _tbStatistics = base.CreateObjectSet<tbStatistics>("tbStatistics");
                }
                return _tbStatistics;
            }
        }
        private ObjectSet<tbStatistics> _tbStatistics;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbTag> tbTag
        {
            get
            {
                if ((_tbTag == null))
                {
                    _tbTag = base.CreateObjectSet<tbTag>("tbTag");
                }
                return _tbTag;
            }
        }
        private ObjectSet<tbTag> _tbTag;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbManager> tbManager
        {
            get
            {
                if ((_tbManager == null))
                {
                    _tbManager = base.CreateObjectSet<tbManager>("tbManager");
                }
                return _tbManager;
            }
        }
        private ObjectSet<tbManager> _tbManager;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbSubscribe> tbSubscribe
        {
            get
            {
                if ((_tbSubscribe == null))
                {
                    _tbSubscribe = base.CreateObjectSet<tbSubscribe>("tbSubscribe");
                }
                return _tbSubscribe;
            }
        }
        private ObjectSet<tbSubscribe> _tbSubscribe;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<viSubscribe> viSubscribe
        {
            get
            {
                if ((_viSubscribe == null))
                {
                    _viSubscribe = base.CreateObjectSet<viSubscribe>("viSubscribe");
                }
                return _viSubscribe;
            }
        }
        private ObjectSet<viSubscribe> _viSubscribe;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbActivity> tbActivity
        {
            get
            {
                if ((_tbActivity == null))
                {
                    _tbActivity = base.CreateObjectSet<tbActivity>("tbActivity");
                }
                return _tbActivity;
            }
        }
        private ObjectSet<tbActivity> _tbActivity;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbVisitedInfo> tbVisitedInfo
        {
            get
            {
                if ((_tbVisitedInfo == null))
                {
                    _tbVisitedInfo = base.CreateObjectSet<tbVisitedInfo>("tbVisitedInfo");
                }
                return _tbVisitedInfo;
            }
        }
        private ObjectSet<tbVisitedInfo> _tbVisitedInfo;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tbComment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbComment(tbComment tbComment)
        {
            base.AddObject("tbComment", tbComment);
        }
    
        /// <summary>
        /// 用于向 tbStatistics EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbStatistics(tbStatistics tbStatistics)
        {
            base.AddObject("tbStatistics", tbStatistics);
        }
    
        /// <summary>
        /// 用于向 tbTag EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbTag(tbTag tbTag)
        {
            base.AddObject("tbTag", tbTag);
        }
    
        /// <summary>
        /// 用于向 tbManager EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbManager(tbManager tbManager)
        {
            base.AddObject("tbManager", tbManager);
        }
    
        /// <summary>
        /// 用于向 tbSubscribe EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbSubscribe(tbSubscribe tbSubscribe)
        {
            base.AddObject("tbSubscribe", tbSubscribe);
        }
    
        /// <summary>
        /// 用于向 viSubscribe EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToviSubscribe(viSubscribe viSubscribe)
        {
            base.AddObject("viSubscribe", viSubscribe);
        }
    
        /// <summary>
        /// 用于向 tbActivity EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbActivity(tbActivity tbActivity)
        {
            base.AddObject("tbActivity", tbActivity);
        }
    
        /// <summary>
        /// 用于向 tbVisitedInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbVisitedInfo(tbVisitedInfo tbVisitedInfo)
        {
            base.AddObject("tbVisitedInfo", tbVisitedInfo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbActivity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbActivity : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbActivity 对象。
        /// </summary>
        /// <param name="activityID">ActivityID 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        /// <param name="tagID">TagID 属性的初始值。</param>
        /// <param name="userEmail">UserEmail 属性的初始值。</param>
        /// <param name="activityIntro">ActivityIntro 属性的初始值。</param>
        /// <param name="header">Header 属性的初始值。</param>
        /// <param name="seetimes">Seetimes 属性的初始值。</param>
        /// <param name="keyword">Keyword 属性的初始值。</param>
        /// <param name="beginTime">BeginTime 属性的初始值。</param>
        /// <param name="endTime">EndTime 属性的初始值。</param>
        public static tbActivity CreatetbActivity(global::System.Int32 activityID, global::System.Int32 type, global::System.Int32 tagID, global::System.String userEmail, global::System.String activityIntro, global::System.String header, global::System.Int32 seetimes, global::System.String keyword, global::System.DateTime beginTime, global::System.DateTime endTime)
        {
            tbActivity tbActivity = new tbActivity();
            tbActivity.ActivityID = activityID;
            tbActivity.Type = type;
            tbActivity.TagID = tagID;
            tbActivity.UserEmail = userEmail;
            tbActivity.ActivityIntro = activityIntro;
            tbActivity.Header = header;
            tbActivity.Seetimes = seetimes;
            tbActivity.Keyword = keyword;
            tbActivity.BeginTime = beginTime;
            tbActivity.EndTime = endTime;
            return tbActivity;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                OnTagIDChanging(value);
                ReportPropertyChanging("TagID");
                _TagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TagID");
                OnTagIDChanged();
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RewardIntro
        {
            get
            {
                return _RewardIntro;
            }
            set
            {
                OnRewardIntroChanging(value);
                ReportPropertyChanging("RewardIntro");
                _RewardIntro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RewardIntro");
                OnRewardIntroChanged();
            }
        }
        private global::System.String _RewardIntro;
        partial void OnRewardIntroChanging(global::System.String value);
        partial void OnRewardIntroChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActivityIntro
        {
            get
            {
                return _ActivityIntro;
            }
            set
            {
                OnActivityIntroChanging(value);
                ReportPropertyChanging("ActivityIntro");
                _ActivityIntro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ActivityIntro");
                OnActivityIntroChanged();
            }
        }
        private global::System.String _ActivityIntro;
        partial void OnActivityIntroChanging(global::System.String value);
        partial void OnActivityIntroChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Header
        {
            get
            {
                return _Header;
            }
            set
            {
                OnHeaderChanging(value);
                ReportPropertyChanging("Header");
                _Header = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Header");
                OnHeaderChanged();
            }
        }
        private global::System.String _Header;
        partial void OnHeaderChanging(global::System.String value);
        partial void OnHeaderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seetimes
        {
            get
            {
                return _Seetimes;
            }
            set
            {
                OnSeetimesChanging(value);
                ReportPropertyChanging("Seetimes");
                _Seetimes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seetimes");
                OnSeetimesChanged();
            }
        }
        private global::System.Int32 _Seetimes;
        partial void OnSeetimesChanging(global::System.Int32 value);
        partial void OnSeetimesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActivityImg
        {
            get
            {
                return _ActivityImg;
            }
            set
            {
                OnActivityImgChanging(value);
                ReportPropertyChanging("ActivityImg");
                _ActivityImg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActivityImg");
                OnActivityImgChanged();
            }
        }
        private global::System.String _ActivityImg;
        partial void OnActivityImgChanging(global::System.String value);
        partial void OnActivityImgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OutLink
        {
            get
            {
                return _OutLink;
            }
            set
            {
                OnOutLinkChanging(value);
                ReportPropertyChanging("OutLink");
                _OutLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OutLink");
                OnOutLinkChanged();
            }
        }
        private global::System.String _OutLink;
        partial void OnOutLinkChanging(global::System.String value);
        partial void OnOutLinkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword
        {
            get
            {
                return _Keyword;
            }
            set
            {
                OnKeywordChanging(value);
                ReportPropertyChanging("Keyword");
                _Keyword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword");
                OnKeywordChanged();
            }
        }
        private global::System.String _Keyword;
        partial void OnKeywordChanging(global::System.String value);
        partial void OnKeywordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                OnBeginTimeChanging(value);
                ReportPropertyChanging("BeginTime");
                _BeginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BeginTime");
                OnBeginTimeChanged();
            }
        }
        private global::System.DateTime _BeginTime;
        partial void OnBeginTimeChanging(global::System.DateTime value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.DateTime _EndTime;
        partial void OnEndTimeChanging(global::System.DateTime value);
        partial void OnEndTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbComment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbComment 对象。
        /// </summary>
        /// <param name="commentID">CommentID 属性的初始值。</param>
        /// <param name="activityID">ActivityID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="commentContent">CommentContent 属性的初始值。</param>
        /// <param name="commentDate">CommentDate 属性的初始值。</param>
        /// <param name="userAvatar">UserAvatar 属性的初始值。</param>
        public static tbComment CreatetbComment(global::System.Int32 commentID, global::System.Int32 activityID, global::System.String userName, global::System.String commentContent, global::System.DateTime commentDate, global::System.String userAvatar)
        {
            tbComment tbComment = new tbComment();
            tbComment.CommentID = commentID;
            tbComment.ActivityID = activityID;
            tbComment.UserName = userName;
            tbComment.CommentContent = commentContent;
            tbComment.CommentDate = commentDate;
            tbComment.UserAvatar = userAvatar;
            return tbComment;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                if (_CommentID != value)
                {
                    OnCommentIDChanging(value);
                    ReportPropertyChanging("CommentID");
                    _CommentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentID");
                    OnCommentIDChanged();
                }
            }
        }
        private global::System.Int32 _CommentID;
        partial void OnCommentIDChanging(global::System.Int32 value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                OnActivityIDChanging(value);
                ReportPropertyChanging("ActivityID");
                _ActivityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivityID");
                OnActivityIDChanged();
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentContent
        {
            get
            {
                return _CommentContent;
            }
            set
            {
                OnCommentContentChanging(value);
                ReportPropertyChanging("CommentContent");
                _CommentContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentContent");
                OnCommentContentChanged();
            }
        }
        private global::System.String _CommentContent;
        partial void OnCommentContentChanging(global::System.String value);
        partial void OnCommentContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CommentDate
        {
            get
            {
                return _CommentDate;
            }
            set
            {
                OnCommentDateChanging(value);
                ReportPropertyChanging("CommentDate");
                _CommentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentDate");
                OnCommentDateChanged();
            }
        }
        private global::System.DateTime _CommentDate;
        partial void OnCommentDateChanging(global::System.DateTime value);
        partial void OnCommentDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserAvatar
        {
            get
            {
                return _UserAvatar;
            }
            set
            {
                OnUserAvatarChanging(value);
                ReportPropertyChanging("UserAvatar");
                _UserAvatar = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserAvatar");
                OnUserAvatarChanged();
            }
        }
        private global::System.String _UserAvatar;
        partial void OnUserAvatarChanging(global::System.String value);
        partial void OnUserAvatarChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbManager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbManager : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbManager 对象。
        /// </summary>
        /// <param name="managerID">ManagerID 属性的初始值。</param>
        /// <param name="managerUserName">ManagerUserName 属性的初始值。</param>
        /// <param name="managerName">ManagerName 属性的初始值。</param>
        /// <param name="managerPwd">ManagerPwd 属性的初始值。</param>
        /// <param name="managerEmail">ManagerEmail 属性的初始值。</param>
        /// <param name="managerTel">ManagerTel 属性的初始值。</param>
        /// <param name="managerStatus">ManagerStatus 属性的初始值。</param>
        /// <param name="registerTime">RegisterTime 属性的初始值。</param>
        /// <param name="lastLoginTime">LastLoginTime 属性的初始值。</param>
        /// <param name="authority">Authority 属性的初始值。</param>
        public static tbManager CreatetbManager(global::System.Int32 managerID, global::System.String managerUserName, global::System.String managerName, global::System.String managerPwd, global::System.String managerEmail, global::System.String managerTel, global::System.Int32 managerStatus, global::System.DateTime registerTime, global::System.DateTime lastLoginTime, global::System.Int32 authority)
        {
            tbManager tbManager = new tbManager();
            tbManager.ManagerID = managerID;
            tbManager.ManagerUserName = managerUserName;
            tbManager.ManagerName = managerName;
            tbManager.ManagerPwd = managerPwd;
            tbManager.ManagerEmail = managerEmail;
            tbManager.ManagerTel = managerTel;
            tbManager.ManagerStatus = managerStatus;
            tbManager.RegisterTime = registerTime;
            tbManager.LastLoginTime = lastLoginTime;
            tbManager.Authority = authority;
            return tbManager;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                if (_ManagerID != value)
                {
                    OnManagerIDChanging(value);
                    ReportPropertyChanging("ManagerID");
                    _ManagerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ManagerID");
                    OnManagerIDChanged();
                }
            }
        }
        private global::System.Int32 _ManagerID;
        partial void OnManagerIDChanging(global::System.Int32 value);
        partial void OnManagerIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerUserName
        {
            get
            {
                return _ManagerUserName;
            }
            set
            {
                OnManagerUserNameChanging(value);
                ReportPropertyChanging("ManagerUserName");
                _ManagerUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManagerUserName");
                OnManagerUserNameChanged();
            }
        }
        private global::System.String _ManagerUserName;
        partial void OnManagerUserNameChanging(global::System.String value);
        partial void OnManagerUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerName
        {
            get
            {
                return _ManagerName;
            }
            set
            {
                OnManagerNameChanging(value);
                ReportPropertyChanging("ManagerName");
                _ManagerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManagerName");
                OnManagerNameChanged();
            }
        }
        private global::System.String _ManagerName;
        partial void OnManagerNameChanging(global::System.String value);
        partial void OnManagerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerPwd
        {
            get
            {
                return _ManagerPwd;
            }
            set
            {
                OnManagerPwdChanging(value);
                ReportPropertyChanging("ManagerPwd");
                _ManagerPwd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManagerPwd");
                OnManagerPwdChanged();
            }
        }
        private global::System.String _ManagerPwd;
        partial void OnManagerPwdChanging(global::System.String value);
        partial void OnManagerPwdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerEmail
        {
            get
            {
                return _ManagerEmail;
            }
            set
            {
                OnManagerEmailChanging(value);
                ReportPropertyChanging("ManagerEmail");
                _ManagerEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManagerEmail");
                OnManagerEmailChanged();
            }
        }
        private global::System.String _ManagerEmail;
        partial void OnManagerEmailChanging(global::System.String value);
        partial void OnManagerEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ManagerTel
        {
            get
            {
                return _ManagerTel;
            }
            set
            {
                OnManagerTelChanging(value);
                ReportPropertyChanging("ManagerTel");
                _ManagerTel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ManagerTel");
                OnManagerTelChanged();
            }
        }
        private global::System.String _ManagerTel;
        partial void OnManagerTelChanging(global::System.String value);
        partial void OnManagerTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ManagerStatus
        {
            get
            {
                return _ManagerStatus;
            }
            set
            {
                OnManagerStatusChanging(value);
                ReportPropertyChanging("ManagerStatus");
                _ManagerStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ManagerStatus");
                OnManagerStatusChanged();
            }
        }
        private global::System.Int32 _ManagerStatus;
        partial void OnManagerStatusChanging(global::System.Int32 value);
        partial void OnManagerStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegisterTime
        {
            get
            {
                return _RegisterTime;
            }
            set
            {
                OnRegisterTimeChanging(value);
                ReportPropertyChanging("RegisterTime");
                _RegisterTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegisterTime");
                OnRegisterTimeChanged();
            }
        }
        private global::System.DateTime _RegisterTime;
        partial void OnRegisterTimeChanging(global::System.DateTime value);
        partial void OnRegisterTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLoginTime
        {
            get
            {
                return _LastLoginTime;
            }
            set
            {
                OnLastLoginTimeChanging(value);
                ReportPropertyChanging("LastLoginTime");
                _LastLoginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginTime");
                OnLastLoginTimeChanged();
            }
        }
        private global::System.DateTime _LastLoginTime;
        partial void OnLastLoginTimeChanging(global::System.DateTime value);
        partial void OnLastLoginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Authority
        {
            get
            {
                return _Authority;
            }
            set
            {
                OnAuthorityChanging(value);
                ReportPropertyChanging("Authority");
                _Authority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Authority");
                OnAuthorityChanged();
            }
        }
        private global::System.Int32 _Authority;
        partial void OnAuthorityChanging(global::System.Int32 value);
        partial void OnAuthorityChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbStatistics")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbStatistics : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbStatistics 对象。
        /// </summary>
        /// <param name="statisticsID">StatisticsID 属性的初始值。</param>
        /// <param name="activityID">ActivityID 属性的初始值。</param>
        /// <param name="haowan">Haowan 属性的初始值。</param>
        /// <param name="jiazhi">Jiazhi 属性的初始值。</param>
        /// <param name="tuhao">Tuhao 属性的初始值。</param>
        /// <param name="meijin">Meijin 属性的初始值。</param>
        /// <param name="chedan">Chedan 属性的初始值。</param>
        /// <param name="c_Haowan">C_Haowan 属性的初始值。</param>
        /// <param name="c_Jiazhi">C_Jiazhi 属性的初始值。</param>
        /// <param name="c_Tuhao">C_Tuhao 属性的初始值。</param>
        /// <param name="c_Meijin">C_Meijin 属性的初始值。</param>
        /// <param name="c_Chedan">C_Chedan 属性的初始值。</param>
        public static tbStatistics CreatetbStatistics(global::System.Int32 statisticsID, global::System.Int32 activityID, global::System.Int32 haowan, global::System.Int32 jiazhi, global::System.Int32 tuhao, global::System.Int32 meijin, global::System.Int32 chedan, global::System.Int32 c_Haowan, global::System.Int32 c_Jiazhi, global::System.Int32 c_Tuhao, global::System.Int32 c_Meijin, global::System.Int32 c_Chedan)
        {
            tbStatistics tbStatistics = new tbStatistics();
            tbStatistics.StatisticsID = statisticsID;
            tbStatistics.ActivityID = activityID;
            tbStatistics.Haowan = haowan;
            tbStatistics.Jiazhi = jiazhi;
            tbStatistics.Tuhao = tuhao;
            tbStatistics.Meijin = meijin;
            tbStatistics.Chedan = chedan;
            tbStatistics.C_Haowan = c_Haowan;
            tbStatistics.C_Jiazhi = c_Jiazhi;
            tbStatistics.C_Tuhao = c_Tuhao;
            tbStatistics.C_Meijin = c_Meijin;
            tbStatistics.C_Chedan = c_Chedan;
            return tbStatistics;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatisticsID
        {
            get
            {
                return _StatisticsID;
            }
            set
            {
                if (_StatisticsID != value)
                {
                    OnStatisticsIDChanging(value);
                    ReportPropertyChanging("StatisticsID");
                    _StatisticsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatisticsID");
                    OnStatisticsIDChanged();
                }
            }
        }
        private global::System.Int32 _StatisticsID;
        partial void OnStatisticsIDChanging(global::System.Int32 value);
        partial void OnStatisticsIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                OnActivityIDChanging(value);
                ReportPropertyChanging("ActivityID");
                _ActivityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivityID");
                OnActivityIDChanged();
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Haowan
        {
            get
            {
                return _Haowan;
            }
            set
            {
                OnHaowanChanging(value);
                ReportPropertyChanging("Haowan");
                _Haowan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Haowan");
                OnHaowanChanged();
            }
        }
        private global::System.Int32 _Haowan;
        partial void OnHaowanChanging(global::System.Int32 value);
        partial void OnHaowanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Jiazhi
        {
            get
            {
                return _Jiazhi;
            }
            set
            {
                OnJiazhiChanging(value);
                ReportPropertyChanging("Jiazhi");
                _Jiazhi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jiazhi");
                OnJiazhiChanged();
            }
        }
        private global::System.Int32 _Jiazhi;
        partial void OnJiazhiChanging(global::System.Int32 value);
        partial void OnJiazhiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tuhao
        {
            get
            {
                return _Tuhao;
            }
            set
            {
                OnTuhaoChanging(value);
                ReportPropertyChanging("Tuhao");
                _Tuhao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tuhao");
                OnTuhaoChanged();
            }
        }
        private global::System.Int32 _Tuhao;
        partial void OnTuhaoChanging(global::System.Int32 value);
        partial void OnTuhaoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Meijin
        {
            get
            {
                return _Meijin;
            }
            set
            {
                OnMeijinChanging(value);
                ReportPropertyChanging("Meijin");
                _Meijin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Meijin");
                OnMeijinChanged();
            }
        }
        private global::System.Int32 _Meijin;
        partial void OnMeijinChanging(global::System.Int32 value);
        partial void OnMeijinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Chedan
        {
            get
            {
                return _Chedan;
            }
            set
            {
                OnChedanChanging(value);
                ReportPropertyChanging("Chedan");
                _Chedan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Chedan");
                OnChedanChanged();
            }
        }
        private global::System.Int32 _Chedan;
        partial void OnChedanChanging(global::System.Int32 value);
        partial void OnChedanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_Haowan
        {
            get
            {
                return _C_Haowan;
            }
            set
            {
                OnC_HaowanChanging(value);
                ReportPropertyChanging("C_Haowan");
                _C_Haowan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_Haowan");
                OnC_HaowanChanged();
            }
        }
        private global::System.Int32 _C_Haowan;
        partial void OnC_HaowanChanging(global::System.Int32 value);
        partial void OnC_HaowanChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_Jiazhi
        {
            get
            {
                return _C_Jiazhi;
            }
            set
            {
                OnC_JiazhiChanging(value);
                ReportPropertyChanging("C_Jiazhi");
                _C_Jiazhi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_Jiazhi");
                OnC_JiazhiChanged();
            }
        }
        private global::System.Int32 _C_Jiazhi;
        partial void OnC_JiazhiChanging(global::System.Int32 value);
        partial void OnC_JiazhiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_Tuhao
        {
            get
            {
                return _C_Tuhao;
            }
            set
            {
                OnC_TuhaoChanging(value);
                ReportPropertyChanging("C_Tuhao");
                _C_Tuhao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_Tuhao");
                OnC_TuhaoChanged();
            }
        }
        private global::System.Int32 _C_Tuhao;
        partial void OnC_TuhaoChanging(global::System.Int32 value);
        partial void OnC_TuhaoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_Meijin
        {
            get
            {
                return _C_Meijin;
            }
            set
            {
                OnC_MeijinChanging(value);
                ReportPropertyChanging("C_Meijin");
                _C_Meijin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_Meijin");
                OnC_MeijinChanged();
            }
        }
        private global::System.Int32 _C_Meijin;
        partial void OnC_MeijinChanging(global::System.Int32 value);
        partial void OnC_MeijinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_Chedan
        {
            get
            {
                return _C_Chedan;
            }
            set
            {
                OnC_ChedanChanging(value);
                ReportPropertyChanging("C_Chedan");
                _C_Chedan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_Chedan");
                OnC_ChedanChanged();
            }
        }
        private global::System.Int32 _C_Chedan;
        partial void OnC_ChedanChanging(global::System.Int32 value);
        partial void OnC_ChedanChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbSubscribe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbSubscribe : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbSubscribe 对象。
        /// </summary>
        /// <param name="subscribeID">SubscribeID 属性的初始值。</param>
        /// <param name="activityID">ActivityID 属性的初始值。</param>
        /// <param name="userEmail">UserEmail 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static tbSubscribe CreatetbSubscribe(global::System.Int32 subscribeID, global::System.Int32 activityID, global::System.String userEmail, global::System.Int32 status)
        {
            tbSubscribe tbSubscribe = new tbSubscribe();
            tbSubscribe.SubscribeID = subscribeID;
            tbSubscribe.ActivityID = activityID;
            tbSubscribe.UserEmail = userEmail;
            tbSubscribe.Status = status;
            return tbSubscribe;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubscribeID
        {
            get
            {
                return _SubscribeID;
            }
            set
            {
                if (_SubscribeID != value)
                {
                    OnSubscribeIDChanging(value);
                    ReportPropertyChanging("SubscribeID");
                    _SubscribeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubscribeID");
                    OnSubscribeIDChanged();
                }
            }
        }
        private global::System.Int32 _SubscribeID;
        partial void OnSubscribeIDChanging(global::System.Int32 value);
        partial void OnSubscribeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                OnActivityIDChanging(value);
                ReportPropertyChanging("ActivityID");
                _ActivityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActivityID");
                OnActivityIDChanged();
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbTag : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbTag 对象。
        /// </summary>
        /// <param name="tagID">TagID 属性的初始值。</param>
        /// <param name="tagName">TagName 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        public static tbTag CreatetbTag(global::System.Int32 tagID, global::System.String tagName, global::System.Int32 type)
        {
            tbTag tbTag = new tbTag();
            tbTag.TagID = tagID;
            tbTag.TagName = tagName;
            tbTag.Type = type;
            return tbTag;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                if (_TagID != value)
                {
                    OnTagIDChanging(value);
                    ReportPropertyChanging("TagID");
                    _TagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagID");
                    OnTagIDChanged();
                }
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TagName
        {
            get
            {
                return _TagName;
            }
            set
            {
                OnTagNameChanging(value);
                ReportPropertyChanging("TagName");
                _TagName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TagName");
                OnTagNameChanged();
            }
        }
        private global::System.String _TagName;
        partial void OnTagNameChanging(global::System.String value);
        partial void OnTagNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="tbVisitedInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbVisitedInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbVisitedInfo 对象。
        /// </summary>
        /// <param name="iP_Address">IP_Address 属性的初始值。</param>
        /// <param name="iP_DateTime">IP_DateTime 属性的初始值。</param>
        public static tbVisitedInfo CreatetbVisitedInfo(global::System.String iP_Address, global::System.DateTime iP_DateTime)
        {
            tbVisitedInfo tbVisitedInfo = new tbVisitedInfo();
            tbVisitedInfo.IP_Address = iP_Address;
            tbVisitedInfo.IP_DateTime = iP_DateTime;
            return tbVisitedInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP_Address
        {
            get
            {
                return _IP_Address;
            }
            set
            {
                if (_IP_Address != value)
                {
                    OnIP_AddressChanging(value);
                    ReportPropertyChanging("IP_Address");
                    _IP_Address = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IP_Address");
                    OnIP_AddressChanged();
                }
            }
        }
        private global::System.String _IP_Address;
        partial void OnIP_AddressChanging(global::System.String value);
        partial void OnIP_AddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP_Src
        {
            get
            {
                return _IP_Src;
            }
            set
            {
                OnIP_SrcChanging(value);
                ReportPropertyChanging("IP_Src");
                _IP_Src = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP_Src");
                OnIP_SrcChanged();
            }
        }
        private global::System.String _IP_Src;
        partial void OnIP_SrcChanging(global::System.String value);
        partial void OnIP_SrcChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime IP_DateTime
        {
            get
            {
                return _IP_DateTime;
            }
            set
            {
                OnIP_DateTimeChanging(value);
                ReportPropertyChanging("IP_DateTime");
                _IP_DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IP_DateTime");
                OnIP_DateTimeChanged();
            }
        }
        private global::System.DateTime _IP_DateTime;
        partial void OnIP_DateTimeChanging(global::System.DateTime value);
        partial void OnIP_DateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ActivityMDModel", Name="viSubscribe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class viSubscribe : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 viSubscribe 对象。
        /// </summary>
        /// <param name="activityID">ActivityID 属性的初始值。</param>
        /// <param name="expr1">Expr1 属性的初始值。</param>
        /// <param name="beginTime">BeginTime 属性的初始值。</param>
        /// <param name="userEmail">UserEmail 属性的初始值。</param>
        /// <param name="subscribeID">SubscribeID 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static viSubscribe CreateviSubscribe(global::System.Int32 activityID, global::System.Int32 expr1, global::System.DateTime beginTime, global::System.String userEmail, global::System.Int32 subscribeID, global::System.Int32 status)
        {
            viSubscribe viSubscribe = new viSubscribe();
            viSubscribe.ActivityID = activityID;
            viSubscribe.Expr1 = expr1;
            viSubscribe.BeginTime = beginTime;
            viSubscribe.UserEmail = userEmail;
            viSubscribe.SubscribeID = subscribeID;
            viSubscribe.Status = status;
            return viSubscribe;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Expr1
        {
            get
            {
                return _Expr1;
            }
            set
            {
                if (_Expr1 != value)
                {
                    OnExpr1Changing(value);
                    ReportPropertyChanging("Expr1");
                    _Expr1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Expr1");
                    OnExpr1Changed();
                }
            }
        }
        private global::System.Int32 _Expr1;
        partial void OnExpr1Changing(global::System.Int32 value);
        partial void OnExpr1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                if (_BeginTime != value)
                {
                    OnBeginTimeChanging(value);
                    ReportPropertyChanging("BeginTime");
                    _BeginTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BeginTime");
                    OnBeginTimeChanged();
                }
            }
        }
        private global::System.DateTime _BeginTime;
        partial void OnBeginTimeChanging(global::System.DateTime value);
        partial void OnBeginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                if (_UserEmail != value)
                {
                    OnUserEmailChanging(value);
                    ReportPropertyChanging("UserEmail");
                    _UserEmail = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserEmail");
                    OnUserEmailChanged();
                }
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubscribeID
        {
            get
            {
                return _SubscribeID;
            }
            set
            {
                if (_SubscribeID != value)
                {
                    OnSubscribeIDChanging(value);
                    ReportPropertyChanging("SubscribeID");
                    _SubscribeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubscribeID");
                    OnSubscribeIDChanged();
                }
            }
        }
        private global::System.Int32 _SubscribeID;
        partial void OnSubscribeIDChanging(global::System.Int32 value);
        partial void OnSubscribeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                if (_Status != value)
                {
                    OnStatusChanging(value);
                    ReportPropertyChanging("Status");
                    _Status = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Status");
                    OnStatusChanged();
                }
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion

    
    }

    #endregion

    
}
